
project_id = "hrpchhrykumcdeolvtfs"

# Torna a função pública para que o Stripe possa chamá-la sem autenticação
[functions.stripe-webhook]
verify_jwt = false

# Especificando o método importmap para garantir compatibilidade com os módulos
import_map = "./import_map.json"
